---
- name: Create VLAN on usual mikrotik
  hosts: mikrotik
  vars:
    id_vlan: 55
  gather_facts: false
  tasks:
    - name: Run on usual
      community.routeros.command:
        commands:  
          - /interface bridge vlan add bridge=BridgevMotion tagged="BridgevMotion,ether1,ether2,ether3,ether4,\
            ether5,ether6,ether7,ether8,ether9,ether10,ether11,ether12,ether13,ether14,ether15,ether16,ether17,\
            ether18,ether19,ether20,ether21,ether22,ether23,ether24,sfp-sfpplus1,sfp-sfpplus2,\
            sfp-sfpplus3,sfp-sfpplus4" vlan-ids={{id_vlan}}
- name: Create VLAN on optical mikrotik
  hosts: mikrotikopt
  vars:
    id_vlan: 55
  gather_facts: false
  tasks:
    - name: Run on optical
      community.routeros.command:
        commands:
          - /interface bridge vlan add bridge=BridgevMotion tagged="BridgevMotion,combo1,combo2, combo3,combo4,\
            sfp-sfpplus1,sfp-sfpplus2,sfp-sfpplus3,sfp-sfpplus4,sfp1,sfp2,sfp3,sfp4,sfp5,sfp6,sfp7,sfp8,sfp9,\
            sfp10,sfp11,sfp12,sfp13,sfp14,sfp15,sfp16,sfp17,sfp18,sfp19,sfp20" vlan-ids={{id_vlan}}
