- name: Prepare VM from Template
  hosts: test
  become: yes
  gather_facts: yes
  
  vars:
    name_vm: arunner
    
  tasks:   
  - name: Update repository
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
 
  - name: Install open-vm-tools
    apt: name=open-vm-tools state=present
    
  - name: Install curl
    apt: name=curl
    
  - name: Update packages
    apt: upgrade=dist force_apt_get=yes
    
  - name: Change name VM
    command: hostnamectl set-hostname {{name_vm}}
    
  - name: Reboot host
    ansible.builtin.reboot:
  
  - name: Wait after reboot
    ansible.builtin.pause:
      minutes: 2
    
  - name: Check connection
    ansible.builtin.ping:
    
  
