- name: Prepare VM from Template
  hosts: k8scluster
  become: yes
  
  vars:
    source_file: /etc/default/locale
    destin_file: /etc/default/locale
  
  tasks:
  - name: Copy locale to remote server
    copy: src={{ source_file }} dest={{ destin_file }}
      
  - name: Update repository
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
 
  - name: Install open-vm-tools
    apt: name=open-vm-tools state=present
    
  - name: Install curl
    apt: name=curl
    
  - name: Update packages
    apt: upgrade=dist force_apt_get=yes
    
  - name: Reboot host
    ansible.builtin.reboot:
  
  - name: Wait after reboot
    ansible.builtin.pause:
      minutes: 2
    
  - name: Check connection
    ansible.builtin.ping:
    
  
